import { z } from "zod";

const toNumber = (value: string | undefined, fallback: number) => {
  if (!value) return fallback;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const toBool = (value: string | undefined, fallback: boolean) => {
  if (value === undefined) return fallback;
  return value === "true" || value === "1" || value === "yes";
};

const schema = z.object({
  NODE_ENV: z.string().optional().default("development"),
  PORT: z.string().optional().default("4000"),
  REDIS_URL: z.string().min(1),
  DATABASE_URL: z.string().min(1),
  RADIO_ADMIN_API_KEY: z.string().min(8),
  CHESHIRE_BASE_URL: z.string().optional().default(""),
  CHESHIRE_API_KEY: z.string().optional(),
  CHESHIRE_MODEL: z.string().optional().default("gpt-oss:20b"),
  RADIO_CHESHIRE_MODEL: z.string().optional().default(""),
  RADIO_EMBED_MODEL: z.string().optional().default("nomic-embed-text"),
  CHESHIRE_REQUEST_RETRIES: z.string().optional().default("1"),
  CHESHIRE_RETRY_DELAY_MS: z.string().optional().default("300"),
  DJ_REQUEST_TIMEOUT_MS: z.string().optional().default("20000"),
  DJ_LLM_FAILURE_THRESHOLD: z.string().optional().default("3"),
  DJ_LLM_COOLDOWN_MS: z.string().optional().default("180000"),
  MPLAYER_STREAM_URL: z.union([z.string().url(), z.literal("")]).optional().default(""),
  MSTREAM_BASE_URL: z.string().optional(),
  MSTREAM_LIBRARY_ROOT: z.string().optional().default("/library/"),
  MSTREAM_TOKEN: z.string().optional(),
  MUSIC_LIBRARY_PATH: z.string().min(1),
  SNIPPETS_PATH: z.string().min(1),
  PODCAST_LIBRARY_PATH: z.string().min(1),
  PHOTOS_LIBRARY_PATH: z.string().optional().default(""),
  IMMICH_BASE_URL: z.string().optional().default(""),
  IMMICH_API_KEY: z.string().optional().default(""),
  IMMICH_ALBUM_NAME: z.string().optional().default(""),
  IMMICH_ALBUM_ID: z.string().optional().default(""),
  IMMICH_REQUEST_TIMEOUT_MS: z.string().optional().default("12000"),
  LIQUIDSOAP_HOST: z.string().optional().default("liquidsoap"),
  LIQUIDSOAP_TELNET_PORT: z.string().optional().default("1234"),
  LIQUIDSOAP_META_URL: z.string().optional().default("http://icecast:8000/status-json.xsl"),
  LIQUIDSOAP_META_TIMEOUT_MS: z.string().optional().default("3500"),
  STATION_NAME: z.string().optional().default("Mr Rassy Radio"),
  STATION_TIME_ZONE: z.string().optional().default("America/New_York"),
  STATION_DESCRIPTION: z
    .string()
    .optional()
    .default("Live radio from Ian Rasmussen's shelves, with Mr Rassy in the booth."),
  STATION_GENRE: z.string().optional().default("eclectic"),
  STREAM_MOUNT: z.string().optional().default("/live.mp3"),
  ICECAST_SOURCE_PASSWORD: z.string().min(1),
  ICECAST_ADMIN_PASSWORD: z.string().min(1),
  ICECAST_RELAY_PASSWORD: z.string().min(1),
  ICECAST_HOST: z.string().optional().default("icecast"),
  ICECAST_PORT: z.string().optional().default("8000"),
  ICECAST_USERNAME: z.string().optional().default("source"),
  ICECAST_PUBLIC_URL: z.string().optional().default(""),
  RADIO_MOOD: z.string().optional().default("late-night warmth / candlelit drift"),
  RADIO_TRACK_COOLDOWN_HOURS: z.string().optional().default("48"),
  RADIO_TRACK_COOLDOWN_DAYS: z.string().optional().default("7"),
  RADIO_ARTIST_COOLDOWN_TRACKS: z.string().optional().default("10"),
  RADIO_QUEUE_TARGET: z.string().optional().default("6"),
  RADIO_LOCKED_QUEUE_TRACKS: z.string().optional().default("3"),
  RADIO_SET_TARGET_SIZE: z.string().optional().default("11"),
  RADIO_SET_MIN_SIZE: z.string().optional().default("3"),
  RADIO_DECISION_BATCH_SIZE: z.string().optional().default("2"),
  RADIO_SPECIAL_MIN_GAP_HOURS: z.string().optional().default("6"),
  RADIO_SPECIAL_CHANCE: z.string().optional().default("0.24"),
  RADIO_LONG_TRACK_THRESHOLD_SECONDS: z.string().optional().default("720"),
  RADIO_LONG_TRACK_CLIP_SECONDS: z.string().optional().default("300"),
  RADIO_LONG_TRACK_FADE_SECONDS: z.string().optional().default("4"),
  RADIO_LONG_TRACK_EDGE_PADDING_SECONDS: z.string().optional().default("45"),
  RADIO_TRANSITIONS_ENABLED: z.string().optional().default("true"),
  RADIO_TRANSITION_MIN_SONGS: z.string().optional().default("3"),
  RADIO_TRANSITION_MAX_SONGS: z.string().optional().default("10"),
  RADIO_TRANSITION_MIN_SECONDS: z.string().optional().default("3"),
  RADIO_TRANSITION_MAX_SECONDS: z.string().optional().default("8"),
  RADIO_SNIPPET_CHANCE: z.string().optional().default("0.12"),
  RADIO_SNIPPET_COOLDOWN_TRACKS: z.string().optional().default("12"),
  RADIO_SELF_SNIPPET_WEIGHT: z.string().optional().default("0.18"),
  RADIO_SNIPPET_MIN_GAP_MINUTES: z.string().optional().default("60"),
  RADIO_SNIPPET_TRIM_THRESHOLD_SECONDS: z.string().optional().default("180"),
  RADIO_SNIPPET_PLAY_WINDOW_SECONDS: z.string().optional().default("120"),
  RADIO_MIN_TALK_MINUTES: z.string().optional().default("18"),
  RADIO_LIBRARY_REFRESH_SECONDS: z.string().optional().default("30"),
  RADIO_HEARS_INLINE_TIMEOUT_MS: z.string().optional().default("4500"),
  RADIO_HEARS_BACKGROUND_MIN_INTERVAL_MS: z.string().optional().default("600000"),
  RADIO_CHAT_ACTIVITY_GRACE_MS: z.string().optional().default("120000"),
  RADIO_TRACK_ANALYSIS_TIMEOUT_MS: z.string().optional().default("9000"),
  RADIO_TRACK_ANALYSIS_COOLDOWN_HOURS: z.string().optional().default("96"),
  RADIO_KNOWLEDGE_BOOTSTRAP_LIMIT: z.string().optional().default("240"),
  RADIO_KNOWLEDGE_ANALYSIS_LIMIT: z.string().optional().default("8"),
  RADIO_FEEDBACK_WEIGHT: z.string().optional().default("0.22"),
  TTS_ENABLED: z.string().optional().default("false"),
  TTS_PROVIDER: z.string().optional().default("piper"),
  TTS_ENDPOINT: z.string().optional().default("")
});

const parsed = schema.parse(process.env);

export const config = {
  NODE_ENV: parsed.NODE_ENV,
  PORT: toNumber(parsed.PORT, 4000),
  REDIS_URL: parsed.REDIS_URL,
  DATABASE_URL: parsed.DATABASE_URL,
  RADIO_ADMIN_API_KEY: parsed.RADIO_ADMIN_API_KEY,
  CHESHIRE_BASE_URL: parsed.CHESHIRE_BASE_URL,
  CHESHIRE_API_KEY: parsed.CHESHIRE_API_KEY,
  CHESHIRE_MODEL: parsed.RADIO_CHESHIRE_MODEL || parsed.CHESHIRE_MODEL,
  RADIO_EMBED_MODEL: parsed.RADIO_EMBED_MODEL,
  CHESHIRE_REQUEST_RETRIES: toNumber(parsed.CHESHIRE_REQUEST_RETRIES, 1),
  CHESHIRE_RETRY_DELAY_MS: toNumber(parsed.CHESHIRE_RETRY_DELAY_MS, 300),
  DJ_REQUEST_TIMEOUT_MS: toNumber(parsed.DJ_REQUEST_TIMEOUT_MS, 20000),
  DJ_LLM_FAILURE_THRESHOLD: toNumber(parsed.DJ_LLM_FAILURE_THRESHOLD, 3),
  DJ_LLM_COOLDOWN_MS: toNumber(parsed.DJ_LLM_COOLDOWN_MS, 180000),
  MPLAYER_STREAM_URL: parsed.MPLAYER_STREAM_URL,
  MSTREAM_BASE_URL: parsed.MSTREAM_BASE_URL,
  MSTREAM_LIBRARY_ROOT: parsed.MSTREAM_LIBRARY_ROOT,
  MSTREAM_TOKEN: parsed.MSTREAM_TOKEN,
  MUSIC_LIBRARY_PATH: parsed.MUSIC_LIBRARY_PATH,
  SNIPPETS_PATH: parsed.SNIPPETS_PATH,
  PODCAST_LIBRARY_PATH: parsed.PODCAST_LIBRARY_PATH,
  PHOTOS_LIBRARY_PATH: parsed.PHOTOS_LIBRARY_PATH,
  IMMICH_BASE_URL: parsed.IMMICH_BASE_URL,
  IMMICH_API_KEY: parsed.IMMICH_API_KEY,
  IMMICH_ALBUM_NAME: parsed.IMMICH_ALBUM_NAME,
  IMMICH_ALBUM_ID: parsed.IMMICH_ALBUM_ID,
  IMMICH_REQUEST_TIMEOUT_MS: toNumber(parsed.IMMICH_REQUEST_TIMEOUT_MS, 12000),
  LIQUIDSOAP_HOST: parsed.LIQUIDSOAP_HOST,
  LIQUIDSOAP_TELNET_PORT: toNumber(parsed.LIQUIDSOAP_TELNET_PORT, 1234),
  LIQUIDSOAP_META_URL: parsed.LIQUIDSOAP_META_URL,
  LIQUIDSOAP_META_TIMEOUT_MS: toNumber(parsed.LIQUIDSOAP_META_TIMEOUT_MS, 3500),
  STATION_NAME: parsed.STATION_NAME,
  STATION_TIME_ZONE: parsed.STATION_TIME_ZONE || "America/New_York",
  STATION_DESCRIPTION: parsed.STATION_DESCRIPTION,
  STATION_GENRE: parsed.STATION_GENRE,
  STREAM_MOUNT: parsed.STREAM_MOUNT,
  ICECAST_SOURCE_PASSWORD: parsed.ICECAST_SOURCE_PASSWORD,
  ICECAST_ADMIN_PASSWORD: parsed.ICECAST_ADMIN_PASSWORD,
  ICECAST_RELAY_PASSWORD: parsed.ICECAST_RELAY_PASSWORD,
  ICECAST_HOST: parsed.ICECAST_HOST,
  ICECAST_PORT: toNumber(parsed.ICECAST_PORT, 8000),
  ICECAST_USERNAME: parsed.ICECAST_USERNAME,
  ICECAST_PUBLIC_URL: parsed.ICECAST_PUBLIC_URL,
  RADIO_MOOD: parsed.RADIO_MOOD,
  RADIO_TRACK_COOLDOWN_HOURS: toNumber(parsed.RADIO_TRACK_COOLDOWN_HOURS, 48),
  RADIO_TRACK_COOLDOWN_DAYS: toNumber(parsed.RADIO_TRACK_COOLDOWN_DAYS, 7),
  RADIO_ARTIST_COOLDOWN_TRACKS: toNumber(parsed.RADIO_ARTIST_COOLDOWN_TRACKS, 10),
  RADIO_QUEUE_TARGET: toNumber(parsed.RADIO_QUEUE_TARGET, 6),
  RADIO_LOCKED_QUEUE_TRACKS: toNumber(parsed.RADIO_LOCKED_QUEUE_TRACKS, 3),
  RADIO_SET_TARGET_SIZE: toNumber(parsed.RADIO_SET_TARGET_SIZE, 11),
  RADIO_SET_MIN_SIZE: toNumber(parsed.RADIO_SET_MIN_SIZE, 3),
  RADIO_DECISION_BATCH_SIZE: toNumber(parsed.RADIO_DECISION_BATCH_SIZE, 2),
  RADIO_SPECIAL_MIN_GAP_HOURS: toNumber(parsed.RADIO_SPECIAL_MIN_GAP_HOURS, 6),
  RADIO_SPECIAL_CHANCE: toNumber(parsed.RADIO_SPECIAL_CHANCE, 0.24),
  RADIO_LONG_TRACK_THRESHOLD_SECONDS: toNumber(parsed.RADIO_LONG_TRACK_THRESHOLD_SECONDS, 12 * 60),
  RADIO_LONG_TRACK_CLIP_SECONDS: toNumber(parsed.RADIO_LONG_TRACK_CLIP_SECONDS, 5 * 60),
  RADIO_LONG_TRACK_FADE_SECONDS: toNumber(parsed.RADIO_LONG_TRACK_FADE_SECONDS, 4),
  RADIO_LONG_TRACK_EDGE_PADDING_SECONDS: toNumber(parsed.RADIO_LONG_TRACK_EDGE_PADDING_SECONDS, 45),
  RADIO_TRANSITIONS_ENABLED: toBool(parsed.RADIO_TRANSITIONS_ENABLED, true),
  RADIO_TRANSITION_MIN_SONGS: toNumber(parsed.RADIO_TRANSITION_MIN_SONGS, 3),
  RADIO_TRANSITION_MAX_SONGS: toNumber(parsed.RADIO_TRANSITION_MAX_SONGS, 10),
  RADIO_TRANSITION_MIN_SECONDS: toNumber(parsed.RADIO_TRANSITION_MIN_SECONDS, 3),
  RADIO_TRANSITION_MAX_SECONDS: toNumber(parsed.RADIO_TRANSITION_MAX_SECONDS, 8),
  RADIO_SNIPPET_CHANCE: toNumber(parsed.RADIO_SNIPPET_CHANCE, 0.12),
  RADIO_SNIPPET_COOLDOWN_TRACKS: toNumber(parsed.RADIO_SNIPPET_COOLDOWN_TRACKS, 12),
  RADIO_SELF_SNIPPET_WEIGHT: toNumber(parsed.RADIO_SELF_SNIPPET_WEIGHT, 0.18),
  RADIO_SNIPPET_MIN_GAP_MINUTES: toNumber(parsed.RADIO_SNIPPET_MIN_GAP_MINUTES, 60),
  RADIO_SNIPPET_TRIM_THRESHOLD_SECONDS: toNumber(parsed.RADIO_SNIPPET_TRIM_THRESHOLD_SECONDS, 180),
  RADIO_SNIPPET_PLAY_WINDOW_SECONDS: toNumber(parsed.RADIO_SNIPPET_PLAY_WINDOW_SECONDS, 120),
  RADIO_MIN_TALK_MINUTES: toNumber(parsed.RADIO_MIN_TALK_MINUTES, 18),
  RADIO_LIBRARY_REFRESH_SECONDS: toNumber(parsed.RADIO_LIBRARY_REFRESH_SECONDS, 30),
  RADIO_HEARS_INLINE_TIMEOUT_MS: toNumber(parsed.RADIO_HEARS_INLINE_TIMEOUT_MS, 4500),
  RADIO_HEARS_BACKGROUND_MIN_INTERVAL_MS: toNumber(parsed.RADIO_HEARS_BACKGROUND_MIN_INTERVAL_MS, 600000),
  RADIO_CHAT_ACTIVITY_GRACE_MS: toNumber(parsed.RADIO_CHAT_ACTIVITY_GRACE_MS, 120000),
  RADIO_TRACK_ANALYSIS_TIMEOUT_MS: toNumber(parsed.RADIO_TRACK_ANALYSIS_TIMEOUT_MS, 9000),
  RADIO_TRACK_ANALYSIS_COOLDOWN_HOURS: toNumber(parsed.RADIO_TRACK_ANALYSIS_COOLDOWN_HOURS, 96),
  RADIO_KNOWLEDGE_BOOTSTRAP_LIMIT: toNumber(parsed.RADIO_KNOWLEDGE_BOOTSTRAP_LIMIT, 240),
  RADIO_KNOWLEDGE_ANALYSIS_LIMIT: toNumber(parsed.RADIO_KNOWLEDGE_ANALYSIS_LIMIT, 8),
  RADIO_FEEDBACK_WEIGHT: toNumber(parsed.RADIO_FEEDBACK_WEIGHT, 0.22),
  TTS_ENABLED: toBool(parsed.TTS_ENABLED, false),
  TTS_PROVIDER: parsed.TTS_PROVIDER,
  TTS_ENDPOINT: parsed.TTS_ENDPOINT
};
