services:
  cat:
    environment:
      OLLAMA_GENERAL_BASE_URL: ${OLLAMA_GENERAL_BASE_URL:-http://host.docker.internal:8844}
      OLLAMA_EMBED_BASE_URL: ${OLLAMA_EMBED_BASE_URL:-http://host.docker.internal:8844}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - tipi_main

  cat-support:
    environment:
      OLLAMA_GENERAL_BASE_URL: ${OLLAMA_SUPPORT_GENERAL_BASE_URL:-http://host.docker.internal:8844}
      OLLAMA_EMBED_BASE_URL: ${OLLAMA_SUPPORT_EMBED_BASE_URL:-http://host.docker.internal:8844}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - tipi_main

networks:
  tipi_main:
    external: true
    name: runtipi_tipi_main_network
